name: Actions spring-collab
on:
  - push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: java version
      run: java -version
    - name: Build with Maven
      run: mvn clean install
    
    - name: login and push
      run: |
        docker login -u {{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_PASSWORD }} https://hub.docker.com/
        docker build -t moudjames23/spring-collab:latest .
        docker push moudjames23/spring-collab:latest
    
          
