name: Build Spring-Collab

on:
  push:
    branches: ["main"]


jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3.3.0
      - name: List directories
      - run: "ls -l"


