name: Actions spring-collab
on:
  - push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3

      - name: "List repository files"
        run: "ls -al"
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven
      - name: Setup maven
        run: mvn install
          
