name: Actions spring-collab
on:
  - push
jobs:
  Mkdocs-project:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3

      - name: "List repository files"
        run: "ls -al"
